[package]
name = "linkedlist"
version = "0.1.0"
authors = ["Lingxiang LinG Wang <w93163red@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
